# NumPy

## Fundamentação:

*   Núcleo do Data Science
*   Ótimo para manipulação de arrays multidimensionais
*   Facilidade para manipular grandes dados(feito em C)

"ndarray" = N Dimensional Array


## Criando NumPy Arrays

*   1D

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


### Tentando colocar elementos heterogêneos

In [ ]:
arr = np.array([1, 2, 3, 4, 'teste'])
print(arr)
print(type(arr))

['1' '2' '3' '4' 'teste']
<class 'numpy.ndarray'>


O numpy vai colocar tudo em um único tipo

## Criando uma matriz com numpy

*    2D

In [ ]:
mtz = np.array([[1, 2, 3], [4, 5, 6]])
print(mtz)
print(type(mtz))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


## Funções para estruturar NumPy Arrays

### Array 1D de 1s

In [ ]:
arr = np.ones(15)
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


### Array 2D de 0s

In [ ]:
mtz = np.zeros(10)
print(mtz)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
mtz = np.zeros(10).reshape((5, 2))
print(mtz)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
mtz = np.zeros([5,2])
print(mtz)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


### Arrange

In [ ]:
arr = np.arange(10,31,10) #Até 31 porque o upperbound é exclusivo
print(arr)

[10 20 30]


In [ ]:
arr = np.arange(10,1121,10)
print(arr)

[  10   20   30   40   50   60   70   80   90  100  110  120  130  140
  150  160  170  180  190  200  210  220  230  240  250  260  270  280
  290  300  310  320  330  340  350  360  370  380  390  400  410  420
  430  440  450  460  470  480  490  500  510  520  530  540  550  560
  570  580  590  600  610  620  630  640  650  660  670  680  690  700
  710  720  730  740  750  760  770  780  790  800  810  820  830  840
  850  860  870  880  890  900  910  920  930  940  950  960  970  980
  990 1000 1010 1020 1030 1040 1050 1060 1070 1080 1090 1100 1110 1120]


In [ ]:
#Menor
print(arr.min())

10


In [ ]:
#Maior
print(arr.max())

1120


In [ ]:
#Média
print(arr.mean())

565.0


In [ ]:
#Indice do maior
print(arr.argmax())

111


## Operações com NumPy Arrays

***Para fazer operações, os arrays devem ter o mesmo tamanho***

### Criando os arrays

In [ ]:
arr1 = np.arange(1, 100, 1)
arr2 = np.arange(99, 0, -1)

print(arr1)
print(arr2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]
[99 98 97 96 95 94 93 92 91 90 89 88 87 86 85 84 83 82 81 80 79 78 77 76
 75 74 73 72 71 70 69 68 67 66 65 64 63 62 61 60 59 58 57 56 55 54 53 52
 51 50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28
 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4
  3  2  1]


Somando elemento a elemento com indíces iguais

In [ ]:
print(arr1 + arr2)

[100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100
 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100
 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100
 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100
 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100
 100 100 100 100 100 100 100 100 100]


Multiplicando elemento a elemento com índices iguais

In [ ]:
print(arr1 * arr2)

[  99  196  291  384  475  564  651  736  819  900  979 1056 1131 1204
 1275 1344 1411 1476 1539 1600 1659 1716 1771 1824 1875 1924 1971 2016
 2059 2100 2139 2176 2211 2244 2275 2304 2331 2356 2379 2400 2419 2436
 2451 2464 2475 2484 2491 2496 2499 2500 2499 2496 2491 2484 2475 2464
 2451 2436 2419 2400 2379 2356 2331 2304 2275 2244 2211 2176 2139 2100
 2059 2016 1971 1924 1875 1824 1771 1716 1659 1600 1539 1476 1411 1344
 1275 1204 1131 1056  979  900  819  736  651  564  475  384  291  196
   99]


### Concatenando  

In [ ]:
print(np.concatenate([arr1, arr2]))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99 99 98 97 96 95 94 93 92 91 90 89 88 87 86 85 84 83 82 81 80 79
 78 77 76 75 74 73 72 71 70 69 68 67 66 65 64 63 62 61 60 59 58 57 56 55
 54 53 52 51 50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31
 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7
  6  5  4  3  2  1]


## Operações com matrizes

### Criando a matriz

In [ ]:
mtz = np.array([50, 10, 100, 60, 25, 100, 75, 80, 100]).reshape(3, 3)
print(mtz)

[[ 50  10 100]
 [ 60  25 100]
 [ 75  80 100]]


### Somando as linhas

In [ ]:
print(mtz.sum(axis = 1)) #Para somar linhas

[160 185 255]


### Somando as colunas

In [ ]:
print(mtz.sum(axis = 0)) #Para somar colunas

[185 115 300]


Somando uma coluna específica

In [ ]:
print(mtz.sum(axis = 0)[2])

300


## Broadcasting
-   Você conseguir fazer operações de um vetor com um escalar

In [ ]:
print(mtz/10)

[[ 5.   1.  10. ]
 [ 6.   2.5 10. ]
 [ 7.5  8.  10. ]]


## Brincando com números aleatórios

In [ ]:
#np.random.seed(10) Use isso quando você quiser que o aleatório não seja tão aleatório
arr = np.random.randint(1, 1982568716, 15)
print(arr)

[ 306332348  716454127 1002328759  595807150 1571891772  951580578
  116607770 1381204867 1053072939  858157388 1217447324 1420167187
 1969470769 1713686395 1486000962]


## Brincando com números únicos em conjuntos aleatórios

In [ ]:
arr = np.random.randint(1, 1982568716, 15565)
print(arr)
print(np.unique(arr))
print(np.unique(arr,return_counts=True))

[1543415755 1186308742 1806002373 ... 1213789697 1760955204 1438615977]
[     49671     126137     212319 ... 1982075935 1982242532 1982469920]
(array([     49671,     126137,     212319, ..., 1982075935, 1982242532,
       1982469920]), array([1, 1, 1, ..., 1, 1, 1]))


## Slicing em Numpy Arrays

### Criando um npArray 2D

In [ ]:
mtz = np.arange(0,9000,10).reshape(30,30)
print(mtz)

[[   0   10   20   30   40   50   60   70   80   90  100  110  120  130
   140  150  160  170  180  190  200  210  220  230  240  250  260  270
   280  290]
 [ 300  310  320  330  340  350  360  370  380  390  400  410  420  430
   440  450  460  470  480  490  500  510  520  530  540  550  560  570
   580  590]
 [ 600  610  620  630  640  650  660  670  680  690  700  710  720  730
   740  750  760  770  780  790  800  810  820  830  840  850  860  870
   880  890]
 [ 900  910  920  930  940  950  960  970  980  990 1000 1010 1020 1030
  1040 1050 1060 1070 1080 1090 1100 1110 1120 1130 1140 1150 1160 1170
  1180 1190]
 [1200 1210 1220 1230 1240 1250 1260 1270 1280 1290 1300 1310 1320 1330
  1340 1350 1360 1370 1380 1390 1400 1410 1420 1430 1440 1450 1460 1470
  1480 1490]
 [1500 1510 1520 1530 1540 1550 1560 1570 1580 1590 1600 1610 1620 1630
  1640 1650 1660 1670 1680 1690 1700 1710 1720 1730 1740 1750 1760 1770
  1780 1790]
 [1800 1810 1820 1830 1840 1850 1860 1870 1880 1890 1900 1

### Extraindo apenas uma linha

In [ ]:
print(mtz[2])

[600 610 620 630 640 650 660 670 680 690 700 710 720 730 740 750 760 770
 780 790 800 810 820 830 840 850 860 870 880 890]


### Extraindo apenas uma coluna

In [ ]:
print(mtz[:,-1])

[ 290  590  890 1190 1490 1790 2090 2390 2690 2990 3290 3590 3890 4190
 4490 4790 5090 5390 5690 5990 6290 6590 6890 7190 7490 7790 8090 8390
 8690 8990]


In [ ]:
print(mtz[:,1:])

[[  10   20   30   40   50   60   70   80   90  100  110  120  130  140
   150  160  170  180  190  200  210  220  230  240  250  260  270  280
   290]
 [ 310  320  330  340  350  360  370  380  390  400  410  420  430  440
   450  460  470  480  490  500  510  520  530  540  550  560  570  580
   590]
 [ 610  620  630  640  650  660  670  680  690  700  710  720  730  740
   750  760  770  780  790  800  810  820  830  840  850  860  870  880
   890]
 [ 910  920  930  940  950  960  970  980  990 1000 1010 1020 1030 1040
  1050 1060 1070 1080 1090 1100 1110 1120 1130 1140 1150 1160 1170 1180
  1190]
 [1210 1220 1230 1240 1250 1260 1270 1280 1290 1300 1310 1320 1330 1340
  1350 1360 1370 1380 1390 1400 1410 1420 1430 1440 1450 1460 1470 1480
  1490]
 [1510 1520 1530 1540 1550 1560 1570 1580 1590 1600 1610 1620 1630 1640
  1650 1660 1670 1680 1690 1700 1710 1720 1730 1740 1750 1760 1770 1780
  1790]
 [1810 1820 1830 1840 1850 1860 1870 1880 1890 1900 1910 1920 1930 1940
  1950 1960 1970

## Condicionais no numpy array

In [ ]:
print(mtz>4500)#Vai dar um print de True e False dependendo de quem atender ou não a condição

[[False False False False False False False False False False False False
  False False False False False False False False False False False False
  False False False False False False]
 [False False False False False False False False False False False False
  False False False False False False False False False False False False
  False False False False False False]
 [False False False False False False False False False False False False
  False False False False False False False False False False False False
  False False False False False False]
 [False False False False False False False False False False False False
  False False False False False False False False False False False False
  False False False False False False]
 [False False False False False False False False False False False False
  False False False False False False False False False False False False
  False False False False False False]
 [False False False False False False False False False False Fal

In [ ]:
print(mtz[mtz>4500])#Retorna somente os números que atendem a condição

[4510 4520 4530 4540 4550 4560 4570 4580 4590 4600 4610 4620 4630 4640
 4650 4660 4670 4680 4690 4700 4710 4720 4730 4740 4750 4760 4770 4780
 4790 4800 4810 4820 4830 4840 4850 4860 4870 4880 4890 4900 4910 4920
 4930 4940 4950 4960 4970 4980 4990 5000 5010 5020 5030 5040 5050 5060
 5070 5080 5090 5100 5110 5120 5130 5140 5150 5160 5170 5180 5190 5200
 5210 5220 5230 5240 5250 5260 5270 5280 5290 5300 5310 5320 5330 5340
 5350 5360 5370 5380 5390 5400 5410 5420 5430 5440 5450 5460 5470 5480
 5490 5500 5510 5520 5530 5540 5550 5560 5570 5580 5590 5600 5610 5620
 5630 5640 5650 5660 5670 5680 5690 5700 5710 5720 5730 5740 5750 5760
 5770 5780 5790 5800 5810 5820 5830 5840 5850 5860 5870 5880 5890 5900
 5910 5920 5930 5940 5950 5960 5970 5980 5990 6000 6010 6020 6030 6040
 6050 6060 6070 6080 6090 6100 6110 6120 6130 6140 6150 6160 6170 6180
 6190 6200 6210 6220 6230 6240 6250 6260 6270 6280 6290 6300 6310 6320
 6330 6340 6350 6360 6370 6380 6390 6400 6410 6420 6430 6440 6450 6460
 6470 

In [ ]:
print(mtz[mtz%2==0])

[   0   10   20   30   40   50   60   70   80   90  100  110  120  130
  140  150  160  170  180  190  200  210  220  230  240  250  260  270
  280  290  300  310  320  330  340  350  360  370  380  390  400  410
  420  430  440  450  460  470  480  490  500  510  520  530  540  550
  560  570  580  590  600  610  620  630  640  650  660  670  680  690
  700  710  720  730  740  750  760  770  780  790  800  810  820  830
  840  850  860  870  880  890  900  910  920  930  940  950  960  970
  980  990 1000 1010 1020 1030 1040 1050 1060 1070 1080 1090 1100 1110
 1120 1130 1140 1150 1160 1170 1180 1190 1200 1210 1220 1230 1240 1250
 1260 1270 1280 1290 1300 1310 1320 1330 1340 1350 1360 1370 1380 1390
 1400 1410 1420 1430 1440 1450 1460 1470 1480 1490 1500 1510 1520 1530
 1540 1550 1560 1570 1580 1590 1600 1610 1620 1630 1640 1650 1660 1670
 1680 1690 1700 1710 1720 1730 1740 1750 1760 1770 1780 1790 1800 1810
 1820 1830 1840 1850 1860 1870 1880 1890 1900 1910 1920 1930 1940 1950
 1960 

## Tratamento Textual(subpacote char)

In [ ]:
arr = np.array(['Renzo', 'Soned', 'Ynogut', 'Renan', 'Dani'])
print(arr)

['Renzo' 'Soned' 'Ynogut' 'Renan' 'Dani']


In [ ]:
print(np.char.find(arr, 'R'))#Função que retorna -1 quando não acha e um valor numérico >= para o índice de onde está dentro string o match
print(arr[np.char.find(arr, 'R')!=-1])

[ 0 -1 -1  0 -1]
['Renzo' 'Renan']


## Importando data set no numpy

In [ ]:
ds = np.loadtxt('space.csv', delimiter = ';', dtype = str, encoding='utf-8')
print(ds)

[['\ufeffNum' 'Company Name' 'Location' ... 'Status Rocket' ' Cost'
  'Status Mission']
 ['0' 'SpaceX' 'LC-39A Kennedy Space Center Florida USA' ...
  'StatusActive' '50.0 ' 'Success']
 ['1' 'CASC' 'Site 9401 (SLS-2) Jiuquan Satellite Launch Center China'
  ... 'StatusActive' '29.75 ' 'Success']
 ...
 ['4321' 'US Navy' 'LC-18A Cape Canaveral AFS Florida USA' ...
  'StatusRetired' '0' 'Failure']
 ['4322' 'RVSN USSR' 'Site 1/5 Baikonur Cosmodrome Kazakhstan' ...
  'StatusRetired' '0' 'Success']
 ['4323' 'RVSN USSR' 'Site 1/5 Baikonur Cosmodrome Kazakhstan' ...
  'StatusRetired' '0' 'Success']]


### Colunas do dataset

In [ ]:
print(ds[0])

['\ufeffNum' 'Company Name' 'Location' 'Datum' 'Detail' 'Status Rocket'
 ' Cost' 'Status Mission']


### Calculando a média de uma missão espacial

In [ ]:
#Fazendo um slicing inicial do custo
custo = ds[1:,-2]
print(custo)
#Colocando tudo em float e printando a média dos que colocaram valores
custo = custo.astype(float)
print(custo[custo!=0].mean())

['50.0 ' '29.75 ' '0' ... '0' '0' '0']
153.7921991701245
